<?php
$qrCodeImg  = $this->getPixImg();
$qrCodeCopy = $this->getPixCopy();
?>
<?php if ($qrCodeImg): ?>
    <span><?php echo __($this->getTitle()) ?></span>
    <hr />
    <div style="text-align: center">
        <img width="150" style="margin-bottom: 10px" src="https://www.bcb.gov.br/content/estabilidadefinanceira/piximg/logo_pix.png" />
        <img width="150" style="margin-bottom: 10px" src="<?= $qrCodeImg; ?>" />
        <span style="word-wrap: break-word;"><?= $qrCodeCopy; ?></span>
    </div>
<?php else: ?>
    <span><?php echo __($this->getTitle()) ?></span>
    <br />
    <img width="150" style="margin-bottom: 10px" src="https://www.bcb.gov.br/content/estabilidadefinanceira/piximg/logo_pix.png" />
<?php endif ?>
